



  Performance statistics for DSP solver: icalls =     43

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1800
     no. of nonzeroes in lower triangle of a =           99846
     no. of nonzeroes in the factor l        =          229554
     ratio of nonzeroes in factor (min/max)  =          0.6206
     number of super nodes                   =              50
     maximum order of a front matrix         =             204
     maximum size of a front matrix          =           20910
     maximum size of a front trapezoid       =           19701
     no. of floating point ops for factor    =      2.7054D+07
     no. of floating point ops for solve     =      8.2408D+05
     ratio of flops for factor (min/max)     =          0.5089
     ratio of allocated memory (max/min)     =          1.2581
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     no input or output performed

  Solver Memory allocated on core    0       =        1.283 MB
  Solver Memory allocated on core    1       =        1.321 MB
  Solver Memory allocated on core    2       =        1.106 MB
  Solver Memory allocated on core    3       =        1.050 MB
  Total Solver Memory allocated by all cores =        4.760 MB

