
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           23082
     no. of nonzeroes in lower triangle of a =          803721
     no. of nonzeroes in the factor l        =         4583829
     ratio of nonzeroes in factor (min/max)  =          0.8936
     number of super nodes                   =             880
     maximum order of a front matrix         =             360
     maximum size of a front matrix          =           64980
     maximum size of a front trapezoid       =           52767
     no. of floating point ops for factor    =      9.5243D+08
     no. of floating point ops for solve     =      1.6859D+07
     ratio of flops for factor (min/max)     =          0.9015
     ratio of allocated memory (max/min)     =          1.1332
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.006775
     time (cpu & wall) for ordering          =        0.078125        0.074628
     time (cpu & wall) for other matrix prep =        0.000000        0.009375
     time (cpu & wall) for value input       =        0.015625        0.005069
     time (cpu & wall) for matrix distrib.   =        0.046875        0.048922
     time (cpu & wall) for numeric factor    =        0.062500        0.090257
     computational rate (gflops) for factor  =       15.238877       10.552362

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         63511.        0. MB
                95-   1         65536.        0. MB         55514.        0. MB
                95-   2         65536.        0. MB         59349.        0. MB
                95-   3         65536.        0. MB         52432.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        262144.        2. MB        230806.        2. MB


  Solver Memory allocated on core    0       =       19.884 MB
  Solver Memory allocated on core    1       =       18.218 MB
  Solver Memory allocated on core    2       =       19.074 MB
  Solver Memory allocated on core    3       =       17.547 MB
  Total Solver Memory allocated by all cores =       74.724 MB

