
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1150
     no. of nonzeroes in lower triangle of a =           14296
     no. of nonzeroes in the factor l        =           30108
     ratio of nonzeroes in factor (min/max)  =          0.7750
     number of super nodes                   =              67
     maximum order of a front matrix         =              30
     maximum size of a front matrix          =             465
     maximum size of a front trapezoid       =             444
     no. of floating point ops for factor    =      5.0253D+05
     no. of floating point ops for solve     =      1.1106D+05
     ratio of flops for factor (min/max)     =          0.7863
     ratio of allocated memory (max/min)     =          1.0871
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002799
     time (cpu & wall) for ordering          =        0.000000        0.009800
     time (cpu & wall) for other matrix prep =        0.000000        0.009073
     time (cpu & wall) for value input       =        0.000000        0.001276
     time (cpu & wall) for matrix distrib.   =        0.000000        0.019559
     time (cpu & wall) for numeric factor    =        0.046875        0.070289
     computational rate (gflops) for factor  =        0.010721        0.007149
     time (cpu & wall) for numeric solve     =        0.015625        0.010194
     computational rate (gflops) for solve   =        0.007108        0.010895
     effective I/O rate (GB/sec) for solve   =        0.026482        0.040589

     no input or output performed

  Solver Memory allocated on core    0       =        0.540 MB
  Solver Memory allocated on core    1       =        0.526 MB
  Solver Memory allocated on core    2       =        0.541 MB
  Solver Memory allocated on core    3       =        0.498 MB
  Total Solver Memory allocated by all cores =        2.105 MB

