
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            3120
     no. of nonzeroes in lower triangle of a =          190524
     no. of nonzeroes in the factor l        =          670878
     ratio of nonzeroes in factor (min/max)  =          0.8364
     number of super nodes                   =              81
     maximum order of a front matrix         =             375
     maximum size of a front matrix          =           70500
     maximum size of a front trapezoid       =           45747
     no. of floating point ops for factor    =      1.4153D+08
     no. of floating point ops for solve     =      2.4728D+06
     ratio of flops for factor (min/max)     =          0.7707
     ratio of allocated memory (max/min)     =          1.2239
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001189
     time (cpu & wall) for ordering          =        0.015625        0.012705
     time (cpu & wall) for other matrix prep =        0.000000        0.002655
     time (cpu & wall) for value input       =        0.000000        0.001699
     time (cpu & wall) for matrix distrib.   =        0.015625        0.022529
     time (cpu & wall) for numeric factor    =        0.031250        0.034906
     computational rate (gflops) for factor  =        4.528917        4.054623

     no input or output performed

  Solver Memory allocated on core    0       =        3.776 MB
  Solver Memory allocated on core    1       =        3.701 MB
  Solver Memory allocated on core    2       =        4.147 MB
  Solver Memory allocated on core    3       =        3.388 MB
  Total Solver Memory allocated by all cores =       15.013 MB

