
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1140
     no. of nonzeroes in lower triangle of a =           45579
     no. of nonzeroes in the factor l        =          110800
     ratio of nonzeroes in factor (min/max)  =          0.8295
     number of super nodes                   =              38
     maximum order of a front matrix         =             145
     maximum size of a front matrix          =           10585
     maximum size of a front trapezoid       =            7504
     no. of floating point ops for factor    =      9.6095D+06
     no. of floating point ops for solve     =      3.8970D+05
     ratio of flops for factor (min/max)     =          0.6872
     ratio of allocated memory (max/min)     =          1.0985
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.027000
     time (cpu & wall) for ordering          =        0.015625        0.013000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.004000

     no input or output performed

  Solver Memory allocated on core    0       =        0.888 MB
  Solver Memory allocated on core    1       =        0.830 MB
  Solver Memory allocated on core    2       =        0.911 MB
  Solver Memory allocated on core    3       =        0.862 MB
  Total Solver Memory allocated by all cores =        3.491 MB

