



  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          261487
     no. of nonzeroes in lower triangle of a =        19127908
     no. of nonzeroes in the factor l        =       113125923
     ratio of nonzeroes in factor (min/max)  =          0.3296
     number of super nodes                   =            5236
     maximum order of a front matrix         =             876
     maximum size of a front matrix          =          384126
     maximum size of a front trapezoid       =          280126
     no. of floating point ops for factor    =      5.5764D+10
     no. of floating point ops for solve     =      4.6217D+08
     ratio of flops for factor (min/max)     =          0.4549
     ratio of allocated memory (max/min)     =          2.3835
     negative pivot monitoring activated
     number of negative pivots encountered   =              26
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.062500        0.057087
     time (cpu & wall) for ordering          =        0.546875        0.578068
     time (cpu & wall) for other matrix prep =        0.109375        0.079996
     time (cpu & wall) for value input       =        0.109375        0.120904
     time (cpu & wall) for matrix distrib.   =        0.500000        0.516755
     time (cpu & wall) for numeric factor    =        1.125000        1.134082
     computational rate (gflops) for factor  =       49.567679       49.170725
     time (cpu & wall) for numeric solve     =        0.062500        0.074412
     computational rate (gflops) for solve   =        7.394727        6.211000
     effective I/O rate (GB/sec) for solve   =       27.549692       23.139615

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        720896.        6. MB        693300.        5. MB
                95-   1        655360.        5. MB        630017.        5. MB
                95-   2        327680.        2. MB        308541.        2. MB
                95-   3        458752.        4. MB        435607.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:       2162688.       16. MB       2067465.       16. MB


  Solver Memory allocated on core    0       =      581.417 MB
  Solver Memory allocated on core    1       =      534.296 MB
  Solver Memory allocated on core    2       =      243.932 MB
  Solver Memory allocated on core    3       =      341.730 MB
  Total Solver Memory allocated by all cores =     1701.374 MB

