
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =              15
     no. of nonzeroes in lower triangle of a =              70
     no. of nonzeroes in the factor l        =             458
     ratio of nonzeroes in factor (min/max)  =          0.2258
     number of super nodes                   =               2
     maximum order of a front matrix         =              10
     maximum size of a front matrix          =              55
     maximum size of a front trapezoid       =              55
     no. of floating point ops for factor    =      6.4000D+02
     no. of floating point ops for solve     =      3.0000D+02
     ratio of flops for factor (min/max)     =          0.6582
     ratio of allocated memory (max/min)     =          1.0086
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001171
     time (cpu & wall) for ordering          =        0.000000        0.005018
     time (cpu & wall) for other matrix prep =        0.000000        0.004684
     time (cpu & wall) for value input       =        0.000000        0.000390
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010509

     no input or output performed

  Solver Memory allocated on core    0       =        0.254 MB
  Solver Memory allocated on core    1       =        0.252 MB
  Solver Memory allocated on core    2       =        0.252 MB
  Solver Memory allocated on core    3       =        0.251 MB
  Total Solver Memory allocated by all cores =        1.009 MB

