
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1508
     no. of nonzeroes in lower triangle of a =           22006
     no. of nonzeroes in the factor l        =           83002
     ratio of nonzeroes in factor (min/max)  =          0.8067
     number of super nodes                   =              73
     maximum order of a front matrix         =              94
     maximum size of a front matrix          =            4465
     maximum size of a front trapezoid       =            3475
     no. of floating point ops for factor    =      3.8604D+06
     no. of floating point ops for solve     =      2.7778D+05
     ratio of flops for factor (min/max)     =          0.6473
     ratio of allocated memory (max/min)     =          1.0597
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001041
     time (cpu & wall) for ordering          =        0.000000        0.008159
     time (cpu & wall) for other matrix prep =        0.000000        0.005208
     time (cpu & wall) for value input       =        0.000000        0.000497
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010945
     time (cpu & wall) for numeric factor    =        0.031250        0.028479
     computational rate (gflops) for factor  =        0.123532        0.135552

     no input or output performed

  Solver Memory allocated on core    0       =        0.649 MB
  Solver Memory allocated on core    1       =        0.627 MB
  Solver Memory allocated on core    2       =        0.632 MB
  Solver Memory allocated on core    3       =        0.612 MB
  Total Solver Memory allocated by all cores =        2.520 MB

